<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="geo" uri="/WEB-INF/taglib/geotaglib.tld"%>
<%@ taglib prefix="geoCalc" uri="/WEB-INF/taglib/geocalctaglib.tld"%>
<%@ taglib prefix="utils" uri="/WEB-INF/taglib/stringutilstaglib.tld"%>
<%@ taglib prefix="dttz" uri="/WEB-INF/taglib/datetaglib.tld"%>
<%@ taglib prefix="dttz2" uri="/WEB-INF/taglib/datetaglib2.tld"%>
<%@ taglib prefix="tz" uri="/WEB-INF/taglib/timezonetaglib.tld"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
